version: '3.5'
networks:
    external:
    internal:
services:
    db:
        environment:
            POSTGRES_USER: xthulu
            POSTGRES_DB: xthulu
        image: postgres:12-alpine
        networks:
            - internal
        restart: unless-stopped
        volumes:
            - ./db:/var/lib/postgresql/data:z
    ssh:
        build: .
        command: start
        depends_on:
            - db
        image: xthulu
        networks:
            - internal
            - external
        ports:
            - 8022:8022
        restart: unless-stopped
        volumes:
            - ./data:/app/data
            - ./userland:/app/userland
            - ./xthulu:/app/xthulu
