version: '3.5'

services:

  app:
    build: .
    command: start
    depends_on:
      - db
    environment:
      TERM: xterm-256color
    image: xthulu
    network_mode: host
    restart: unless-stopped
    tty: true
    volumes:
      - ./data:/app/data
      - ./userland:/app/userland

  db:
    environment:
      POSTGRES_USER: xthulu
      POSTGRES_PASSWORD: xthulu
    image: postgres:13-alpine
    ports:
      - "127.0.0.1:5433:5432"
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
