version: '3.5'
services:
    ssh:
        build: .
        image: xthulu
        ports:
            - 8022:8022
        restart: unless-stopped
        volumes:
            - ./data:/app/data
            - ./userland:/app/userland
            - ./xthulu:/app/xthulu
