version: "3"

services:
  ssh:
    volumes:
      - ./xthulu:/app/xthulu

  web:
    volumes:
      - ./xthulu:/app/xthulu

  web-static:
    volumes:
      - ./xthulu/web/static:/usr/share/nginx/html
