version: "3"

services:
  proxy:
    volumes:
      - ./traefik/dynamic.yml:/dynamic.yml:ro
      - ./traefik/traefik.yml:/traefik.yml:ro

  ssh:
    volumes:
      - ./xthulu:/app/xthulu

  web:
    volumes:
      - ./xthulu:/app/xthulu

  web-static:
    volumes:
      - ./xthulu/web/static:/usr/share/nginx/html
