# traefik service configuration

api:
  insecure: true

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: :443

  ssh:
    address: :22

providers:
  docker:
    exposedByDefault: false
    network: xthulu_proxy
    watch: true

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
