name: Checks

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: |
    ${{ github.workflow }}-${{ github.event.pull_request.id || github.branch }}

jobs:
  changes:
    name: Change detection
    runs-on: ubuntu-latest
    outputs:
      misc: ${{ steps.changes.outputs.misc }}
      py: ${{ steps.changes.outputs.py }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Detect changed files
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            ts:
              - "**.js"
              - "**.ts"
            misc:
              - "**.html"
              - "**.json"
              - "**.md"
              - "**.toml"
              - "**.yaml"
              - "**.yml"
            py:
              - "**.py"
              - "requirements/**"
              - pyproject.toml

  # formatting

  ruff-format:
    name: Ruff (formatter)
    needs: changes
    if: needs.changes.outputs.py == 'true' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          pip install -e .[dev]

      - name: Ruff
        run: ruff format --diff .

  prettier:
    name: Prettier (formatter)
    needs: changes
    if: |
      needs.changes.outputs.misc == 'true' ||
      needs.changes.outputs.ts == 'true' ||
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Prettier
        run: npx prettier -lu .

  # linting

  eslint:
    name: ESLint (linter)
    needs: changes
    if: |
      needs.changes.outputs.ts == 'true' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npx eslint .

  ruff-lint:
    name: Ruff (linter)
    needs: changes
    if: needs.changes.outputs.py == 'true' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          pip install -e .[dev]

      - name: Ruff
        run: ruff check --diff .
