name: CommitLint

on:
  pull_request:
    branches: [main]
    types: [opened, edited, reopened, synchronize]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.branch }}

jobs:
  commitlint:
    name: CommitLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint pull request title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE" | npx commitlint
