name: Docker build

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.branch }}

jobs:
  changes:
    name: Change detection
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Detect changed files
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            src:
              - "docker/**"
              - pyproject.toml
              - "requirements/**"
              - "xthulu/**"

  validate:
    name: Validate
    needs: changes
    if: needs.changes.outputs.src == 'true' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Validate docker-compose configuration
        run: docker-compose -f docker/docker-compose.yml config

  build:
    name: Build
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Build docker image
        run: DOCKER_BUILDKIT=1 docker-compose -f docker/docker-compose.yml build
