name: Documentation

on:
  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  build:
    name: pdoc3
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          pip install .
          pip install pdoc3

      - name: Build docs
        run: |
          pdoc3 --html -o html userland xthulu
          cat >html/index.html <<EOF
          <!doctype html>
          <html lang="en-US">
            <head>
              <meta charset="utf-8" />
              <title>xthulu documentation</title>
              <meta name="viewport"
                content="width=device-width,initial-scale=1" />
            </head>
            <body>
              <h1>modules</h1>
              <ul>
                <li>
                  <a href="xthulu/">xthulu</a>
                </li>
                <li>
                  <a href="userland/">userland</a>
                </li>
              </ul>
            </body>
          </html>
          EOF

      - uses: actions/upload-pages-artifact@v3
        with:
          path: html/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
