name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 400

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install semantic-release
        run: |
          pkg="$(grep -E "^python-semantic-release==" requirements/dev.txt)"
          pip install "$pkg"

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: semantic-release version
