name: Tests

on:
  pull_request:

  push:
    branches: [master]

  workflow_dispatch:

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          pip install -e .[dev]

      - name: Unit tests
        run: coverage run --source=xthulu --omit="xthulu/__main__.py"
          -m unittest discover -s tests -v

      - name: Coverage report
        run: |
          total=$(coverage report --format=total)
          echo "**:test_tube: Total coverage: ${total}%**" \
            >> $GITHUB_STEP_SUMMARY
          coverage report --format=markdown >> $GITHUB_STEP_SUMMARY

      - name: Coveralls
        if: github.ref == 'refs/heads/master'
        run: |
          pip install coveralls
          COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_TOKEN }} coveralls
