name: Tests

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: |
    ${{ github.workflow }}-${{ github.event.pull_request.id || github.branch }}

jobs:
  changes:
    name: Change detection
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Detect changed files
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - .editorconfig
              - .prettier-ignore
              - pyproject.toml
              - "requirements/**"
              - "tests/**"
              - "xthulu/**"

  tests:
    name: Unit tests
    needs: changes
    if: needs.changes.outputs.src == 'true' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -U pip setuptools
          pip install -e .[dev]

      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}

      - name: Unit tests
        run: pytest --mypy --cov . --junit-xml junit.xml

      - name: Coverage report
        run: |
          total=$(coverage report --format=total)
          cat >> $GITHUB_STEP_SUMMARY <<EOF
          **:test_tube: :chart_with_upwards_trend: Test coverage: ${total}%**
          EOF
          coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
          coverage xml

      - name: Upload coverage report or add comment
        id: coveralls
        if: always()
        uses: coverallsapp/github-action@v2
        with:
          file: .coverage

      - name: Push result to Testspace server
        if: always() && github.ref_name == 'main'
        run: testspace ./junit.xml ./coverage.xml

      - name: Output Coveralls success/fail
        if: always() && steps.coveralls.outcome == 'failure'
        run: exit 1

  # Re-run in case of 503 from coveralls.io
  retry:
    name: Retry
    needs: tests
    if: failure() && fromJSON(github.run_attempt) < 3
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api
        run: gh workflow run retry.yml -F run_id=${{ github.run_id }}
