name: Tests

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: |
    ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}

jobs:
  changes:
    name: Change detection
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Detect changed files
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - .editorconfig
              - .prettier-ignore
              - pyproject.toml
              - "requirements/**"
              - "tests/**"
              - "xthulu/**"

  tests:
    name: Unit tests
    needs: changes
    if: needs.changes.outputs.src == 'true' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -U pip setuptools
          pip install -e .[dev]

      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}

      - name: Unit tests
        run: pytest --mypy --cov . --junit-xml junit.xml

      - name: Coverage report
        run: |
          total=$(coverage report --format=total)
          cat >> $GITHUB_STEP_SUMMARY <<EOF
          **🧪📈 Test coverage: ${total}%**
          EOF
          coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
          coverage xml

      - name: Upload coverage report or add comment
        id: coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: .coverage

      - name: Push result to Testspace server
        if: always() && contains(github.event_name, 'push') && github.ref_name == 'main'
        run: testspace ./junit.xml ./coverage.xml

      - name: Resolve Coveralls failure
        if: always() && steps.coveralls.outcome == 'failure'
        run: exit 1

  # Clean up retry comment (if any) on success or eventual failure
  finish:
    name: Finish
    needs: tests
    if: contains(github.event_name, 'pull') && (success() || fromJSON(github.run_attempt) >= 3)
    runs-on: ubuntu-latest
    steps:
      - name: Find retry comment
        if: contains(github.event_name, 'pull')
        id: find
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: <a name="retry-workflow"></a>

      - name: Delete comment
        id: delete
        if: fromJSON(github.run_attempt) < 3 && steps.find.outputs.comment-id != 0
        uses: detomarco/delete-comments@1.1.0
        with:
          comment-id: ${{ steps.find.outputs.comment-id }}

      - name: Post failure comment
        if: fromJSON(github.run_attempt) >= 3
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: append
          body: |
            <a name="retry-workflow"></a>❌ `Attempt #${{ github.run_attempt }}` The Coveralls report upload has failed. Retry limit has been reached.

  # Re-run in case of 503 from coveralls.io
  retry:
    name: Retry
    needs: tests
    if: failure() && fromJSON(github.run_attempt) < 3
    runs-on: ubuntu-latest
    steps:
      - name: Find comment
        if: contains(github.event_name, 'pull')
        id: find
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: <a name="retry-workflow"></a>

      - name: Delete existing comment if first run
        id: delete
        if: fromJSON(github.run_attempt) == 1 && steps.find.outputs.comment-id != 0
        uses: detomarco/delete-comments@1.1.0
        with:
          comment-id: ${{ steps.find.outputs.comment-id }}

      - name: Prep retry comment id
        id: comment-id
        run: |
          if [[ "${{ steps.delete.outcome }}" == "success" ]]; then
            echo "id=0" >> $GITHUB_OUTPUT
          else
            echo "id=${{ steps.find.outputs.comment-id }}" >> $GITHUB_OUTPUT
          fi

      - name: Post retry comment
        if: contains(github.event_name, 'pull')
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.comment-id.outputs.id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: append
          body: |
            <a name="retry-workflow"></a>♻️ `Attempt #${{ github.run_attempt }}` The Coveralls report upload has failed. The workflow is being retried.

      - env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api
        run: gh workflow run retry.yml -F run_id=${{ github.run_id }}
